overblog_graphql:
    definitions:
        show_debug_info: "%kernel.debug%"
        cache_dir: "%kernel.project_dir%/config/graphql/generated_classes/"
        schema:
            query: Query
            mutation: RootMutation
        mappings:
            auto_discover: true
            types:
                -
                    types: [yaml, graphql]
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
