overblog_graphql:
    definitions:
        cache_dir: "%kernel.project_dir%/config/graphql/generated_classes/"
        schema:
            query: Query
            mutation: RootMutation
        mappings:
            auto_discover: false
            types:
                -
                    types: [yaml, graphql]
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
