Booking:
  type: object
  config:
    description: "An MeetingRoom"
    fields:
      id:
        type: "Int!"
        description: "The unique ID of the booking."
      user:
        description: "User who booked room"
        type: "User!"
#        resolve: "@=resolver('User', [args])"
      meetind_room:
        description: "Meeting Room"
        type: "MeetingRoom!"
#        resolve: "@=resolver('MeetingRoom', [args])"
