Query:
  type: object
  config:
    description: "Users ORM repository"
    fields:
      user:
        type: "User"
        args:
          id:
            description: "Resolves using the user id."
            type: "Int!"
#          username:
#            description: "Resolves using the user name."
#            type: "String"
        resolve: "@=resolver('User', [args])"
      users:
        type: "[User]"
        args:
          ids:
            description: "Resolves using the user id."
            type: "[Int!]!"
#          username:
#            description: "Resolves using the user name."
#            type: "String"
        resolve: "@=resolver('User', [args])"